name: todo_task
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  provider: ^6.1.4
  intl: ^0.20.2
  flutter_slidable: ^4.0.0
  flutter_spinkit: ^5.2.1
  flutter_screenutil: ^5.9.3


dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true

  fonts:
   - family: Poppins-Light
     fonts:
       - asset: assets/fonts/Poppins-Light.ttf
   - family: Poppins-Medium
     fonts:
       - asset: assets/fonts/Poppins-Medium.ttf    
   - family: Poppins-Regular
     fonts:
       - asset: assets/fonts/Poppins-Regular.ttf   
   - family: Poppins-SemiBold
     fonts:
       - asset: assets/fonts/Poppins-SemiBold.ttf


